#!/bin/sh
set -e
exec 2>&1

. ../functions.sh

install -o root -g root -m 0600 /dev/null /etc/ssh/authorized_keys
etcd_get ssh_authorized_keys > /etc/ssh/authorized_keys

mkdir -pv /var/run/sshd

exec /usr/sbin/sshd -D -e -f sshd_config
