#!/bin/sh
set -e -x

export PATH=/usr/lib/postgresql/9.1/bin:$PATH

if [ ! -d data/PG_VERSION ] ; then
    install -d -m 0700 -o postgres -g postgres data
    chpst -u postgres:postgres initdb `pwd`/data
fi

exec chpst -u postgres:postgres postgres \
    -D `pwd`/data \
    -c config_file=`pwd`/postgresql.conf \
    -c hba_file=`pwd`/pg_hba.conf
