#!/bin/sh
set -e -x

export PATH=/usr/lib/postgresql/9.1/bin:$PATH
datadir=/data/postgresql

if [ ! -e $datadir/PG_VERSION ] ; then
    install -d -m 0700 -o postgres -g postgres $datadir
    chpst -u postgres:postgres initdb $datadir
fi

exec chpst -u postgres:postgres postgres \
    -D $datadir \
    -c config_file=`pwd`/postgresql.conf \
    -c hba_file=`pwd`/pg_hba.conf
